[package]
name = "lrapiut"
version = "0.1.0"
edition = "2021"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
reqwest = { version = "0.11.16", features = ["cookies", "json"] }
serde_json = "1.0"
select = "0.6"