[package]
name = "lrapiut"
version = "0.1.0"
edition = "2021"
author = "Jonas CHARRIER (EarthKiii)"
repository = "https://github.com/EarthKiii/lrapiut/"
homepage = "https://github.com/EarthKiii/lrapiut/"
license = "MIT OR Apache-2.0"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
reqwest = { version = "0.11.16", features = ["cookies", "json"] }
serde_json = "1.0"
select = "0.6"